export enum Material {
    ALUMINUM = 'Aluminum',
    COBALT = 'Cobalt',
    COPPER = 'Copper',
    GLASS = 'Glass',
    GRAPHITE = 'Graphite',
    LITHIUM = 'Lithium',
    MANGANESE = 'Manganese',
    NICKEL = 'Nickel',
    PLASTICS = 'Plastics',
    STEEL = 'Steel',
    IRON = 'Iron',
    PHOSPHATE = 'Phosphate',
    BINDER = 'Binder',
    CONDUCTIVE_ADDITIVE = 'ConductiveAdditive', 
    ELECTROLYTE = 'Electrolyte',
    SEPARATOR = 'Separator',
    RUBBER = 'Rubber',
    RARE_EARTHS = 'RareEarths',
    ELECTRONICS = 'Electronics',
    TEXTILES = 'Textiles',
    FLUIDS = 'Fluids',
    SPECIALIZED_ALLOYS = 'SpecializedAlloys' 
}